    [versions]
    agp = "8.7.3"
    coilCompose = "3.2.0"
    converterGson = "3.0.0"
    koinAndroid = "3.3.0"
    koinAndroidxCompose = "3.3.0"
    koinAndroidxNavigation = "3.3.0"
    kotlin = "2.0.21"
    coreKtx = "1.15.0"
    junit = "4.13.2"
    junitVersion = "1.3.0"
    espressoCore = "3.7.0"
    kotlinxCoroutinesTest = "1.7.3"
    lifecycleRuntimeKtx = "2.9.4"
    activityCompose = "1.9.3"
    composeBom = "2024.09.00"
    sentry = "7.19.0"
    ktlint = "12.1.1"
    mockk = "1.13.8"
    mockitoCore = "5.7.0"
    mockitoKotlin = "5.1.0"
    mockitoInline = "5.2.0"
    turbine = "1.0.0"
    retrofit = "3.0.0"
    navcompose = "2.9.3"
    googleGmsGoogleServices = "4.4.3"
    firebaseDatabase = "22.0.0"
    firebaseFirestore = "25.0.0"
    ksp = "2.0.20-1.0.24"
    room = "2.8.0"
    firebaseMessaging = "25.0.0"
    datastore = "1.0.0"
    firebaseAuth = "23.1.0"
    firebaseBom = "33.8.0"
    coroutinesPlayServices = "1.9.0"
    uiTextGoogleFonts = "1.9.4"
    datastoreCore = "1.1.7"
    material3 = "1.4.0"
    camerax = "1.4.1"
    google-mlkit-barcode-scanning = "17.3.0"
    ui = "1.9.5"
    googleMaps = "19.0.0"
    mapsCompose = "6.2.1"
    playServicesLocation = "21.3.0"
    uiGraphics = "1.9.5"
    lifecycleRuntime = "2.7.0"

    [libraries]
    androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
    androidx-ui-text-google-fonts = { module = "androidx.compose.ui:ui-text-google-fonts", version.ref = "uiTextGoogleFonts" }
    coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
    coil-network = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilCompose" }
    converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
    junit = { group = "junit", name = "junit", version.ref = "junit" }
    androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
    androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
    androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
    androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
    androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
    androidx-ui = { group = "androidx.compose.ui", name = "ui" }
    androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
    androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
    androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
    androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
    androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
    androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
    sentry = { group = "io.sentry", name = "sentry-android", version.ref = "sentry" }
    koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
    koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinAndroidxCompose" }
    koin-androidx-navigation = { module = "io.insert-koin:koin-androidx-navigation", version.ref = "koinAndroidxNavigation" }
    kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
    mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
    mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockitoCore" }
    mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockitoKotlin" }
    mockito-inline = { group = "org.mockito", name = "mockito-inline", version.ref = "mockitoInline" }
    turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
    retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
    androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navcompose"}
    firebase-database = { group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDatabase" }
    firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }
    datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore"}
    androidx-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
    #room
    room-runtime = { group="androidx.room", name="room-runtime", version.ref="room"}
    room-compiler = { group="androidx.room", name="room-compiler", version.ref="room"}
    room-ktx = { group="androidx.room", name="room-ktx", version.ref="room"}
    room-rxjava2 = { group="androidx.room", name="room-rxjava2", version.ref="room"}
    room-rxjava3 = { group="androidx.room", name="room-rxjava3", version.ref="room"}
    room-guava = { group="androidx.room", name="room-guava", version.ref="room"}
    room-testing = { group="androidx.room", name="room-testing", version.ref="room"}
    room-paging = { group="androidx.room", name="room-paging", version.ref="room"}
    firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging", version.ref = "firebaseMessaging" }
    firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
    firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx" }
    firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx" }
    kotlinx-coroutines-play-services = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "coroutinesPlayServices" }
    androidx-datastore-core = { group = "androidx.datastore", name = "datastore-core", version.ref = "datastoreCore" }
    material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
    androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "camerax" }
    androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camerax" }
    androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camerax" }
    androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "camerax" }
    google-mlkit-barcode-scanning = { module = "com.google.mlkit:barcode-scanning", version.ref = "google-mlkit-barcode-scanning" }
    ui = { group = "androidx.compose.ui", name = "ui", version.ref = "ui" }
    google-maps-android = { module = "com.google.android.gms:play-services-maps", version.ref = "googleMaps" }
    maps-compose = { module = "com.google.maps.android:maps-compose", version.ref = "mapsCompose" }
    play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
    ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "uiGraphics" }
    androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleRuntime" }
    androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }


    [plugins]
    android-application = { id = "com.android.application", version.ref = "agp" }
    kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
    kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
    ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
    google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }
    ksp = { id = "com.google.devtools.ksp", version.ref="ksp"}

    [bundles]
    local = ["room-runtime", "room-ktx", "room-rxjava2", "room-rxjava3", "room-guava", "room-paging" ]
    camerax = ["androidx-camera-core", "androidx-camera-camera2", "androidx-camera-lifecycle", "androidx-camera-view"]
    googlemaps = ["google-maps-android", "maps-compose", "play-services-location"]
